export const FETCH_RATES_START = "FETCH_RATES_START";
export const FETCH_RATES_SUCCESS = "FETCH_RATES_SUCCESS";
export const FETCH_RATES_ERROR = "FETCH_RATES_ERROR";
export const CHANGE_BASE = "CHANGE_BASE";

export const CONVERT_START = "CONVERT_START";
export const CONVERT_SUCCESS = "CONVERT_SUCCESS";
export const CONVERT_ERROR = "CONVERT_ERROR";
